application: tsmdigest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: root_static/favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: root_static/robots.txt
  upload: robots\.txt
  
- url: /sitemap\.xml
  static_files: root_static/sitemap.xml
  upload: sitemap\.xml  
  
- url: /assets
  static_dir: assets

- url: /
  script: main.app
  
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
